/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qtriptest;

import java.net.MalformedURLException;

public class App{

    public static void main(String[] args)throws InterruptedException, MalformedURLException  {

    }
}
